### ISSUE TITLE
white space between assessment lines

### ISSUE THREAD

**Issue by lmc150** [rhine3/specky#6]
There is an extra white space between each assessment line.

**Comment by rhine3** [comment]
@lmc150 I didn't have this problem on Mac, so I looked it up on Windows systems. This StackOverflow thread suggested a fix, adding `newline=''` to calls to write to/append to the file: https://stackoverflow.com/questions/3348460/csv-file-written-with-python-has-blank-lines-between-each-row

Let me know if this fixes up the problem on Windows! If it seems to solve the problem, I'll close this issue.

**Comment by lmc150** [comment]
It's fixed!
